// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateShopInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type CreateUserInput struct {
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password *string `json:"password,omitempty"`
	Tel      string  `json:"tel"`
}

type UpdateUserInput struct {
	Username *string `json:"username,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Tel      *string `json:"tel,omitempty"`
}
