// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateUserInput struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
